-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 13:31:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projettrans
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projettrans
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projettrans` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projettrans` ;

-- -----------------------------------------------------
-- Table `projettrans`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`departement` (
  `idDepartement` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartement`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`commune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`commune` (
  `idCommune` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idDepartement` INT(11) NOT NULL,
  PRIMARY KEY (`idCommune`),
  INDEX `idDep_idx` (`idDepartement` ASC) VISIBLE,
  CONSTRAINT `idDep`
    FOREIGN KEY (`idDepartement`)
    REFERENCES `projettrans`.`departement` (`idDepartement`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`espece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`espece` (
  `idEspece` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspece`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`nbespece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`nbespece` (
  `idNbEspece` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` INT(11) NULL DEFAULT NULL,
  `idEspece` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idNbEspece`),
  INDEX `idEspece_idx` (`idEspece` ASC) VISIBLE,
  CONSTRAINT `idEspece`
    FOREIGN KEY (`idEspece`)
    REFERENCES `projettrans`.`espece` (`idEspece`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`groupe` (
  `idGroupe` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroupe`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`personne` (
  `idPersonne` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `idGroupe` INT(11) NOT NULL,
  `passwd` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPersonne`),
  UNIQUE INDEX `idPersonne_UNIQUE` (`idPersonne` ASC) VISIBLE,
  INDEX `idGroupe_idx` (`idGroupe` ASC) VISIBLE,
  CONSTRAINT `idGroupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `projettrans`.`groupe` (`idGroupe`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`etude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`etude` (
  `idEtude` INT(11) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `idChef` INT(11) NOT NULL,
  PRIMARY KEY (`idEtude`),
  INDEX `idChef_idx` (`idChef` ASC) VISIBLE,
  CONSTRAINT `idChef`
    FOREIGN KEY (`idChef`)
    REFERENCES `projettrans`.`personne` (`idPersonne`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`plage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`plage` (
  `idPlage` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idCommune` INT(11) NOT NULL,
  `superficie` INT(11) NOT NULL,
  PRIMARY KEY (`idPlage`),
  INDEX `idCommune_idx` (`idCommune` ASC) VISIBLE,
  CONSTRAINT `idCommune`
    FOREIGN KEY (`idCommune`)
    REFERENCES `projettrans`.`commune` (`idCommune`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`comptage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`comptage` (
  `idcomptage` INT(11) NOT NULL AUTO_INCREMENT,
  `nb_de_part` INT(11) NOT NULL,
  `coordonnées` VARCHAR(50) NOT NULL,
  `idEtude` INT(11) NOT NULL,
  `nbEspeces` INT(11) NOT NULL,
  `idPlage` INT(11) NOT NULL,
  `idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`idcomptage`),
  INDEX `idEtude_idx` (`idEtude` ASC) VISIBLE,
  INDEX `idEspeces_idx` (`nbEspeces` ASC) VISIBLE,
  INDEX `idPlage_idx` (`idPlage` ASC) VISIBLE,
  INDEX `idPersonne_idx` (`idPersonne` ASC) VISIBLE,
  CONSTRAINT `idEspeces`
    FOREIGN KEY (`nbEspeces`)
    REFERENCES `projettrans`.`nbespece` (`idNbEspece`),
  CONSTRAINT `idEtude`
    FOREIGN KEY (`idEtude`)
    REFERENCES `projettrans`.`etude` (`idEtude`),
  CONSTRAINT `idPersonne`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `projettrans`.`personne` (`idPersonne`),
  CONSTRAINT `idPlage`
    FOREIGN KEY (`idPlage`)
    REFERENCES `projettrans`.`plage` (`idPlage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projettrans`.`plage_has_etude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projettrans`.`plage_has_etude` (
  `plage_idPlage` INT(11) NOT NULL,
  `etude_idEtude` INT(11) NOT NULL,
  PRIMARY KEY (`plage_idPlage`, `etude_idEtude`),
  INDEX `fk_plage_has_etude_etude1_idx` (`etude_idEtude` ASC) VISIBLE,
  INDEX `fk_plage_has_etude_plage1_idx` (`plage_idPlage` ASC) VISIBLE,
  CONSTRAINT `fk_plage_has_etude_etude1`
    FOREIGN KEY (`etude_idEtude`)
    REFERENCES `projettrans`.`etude` (`idEtude`),
  CONSTRAINT `fk_plage_has_etude_plage1`
    FOREIGN KEY (`plage_idPlage`)
    REFERENCES `projettrans`.`plage` (`idPlage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
